<?php

declare(strict_types=1);

return [
    'navigationTargets' => [
        [
            'id' => 'dashboard',
            'label' => 'Admin Dashboard',
            'route' => '/admin/dashboard',
            'description' => 'Overall administration overview with key metrics and quick tasks.',
            'keywords' => ['dashboard', 'overview', 'summary', '仪表盘', '总览', '首页'],
        ],
        [
            'id' => 'users',
            'label' => 'User Management',
            'route' => '/admin/users',
            'description' => 'Manage users, roles, points, and account status.',
            'keywords' => ['user', 'account', '用户', '管理用户', '权限'],
        ],
        [
            'id' => 'activities',
            'label' => 'Activity Review',
            'route' => '/admin/activities',
            'description' => 'Review and moderate carbon reduction activity submissions.',
            'keywords' => ['activity', 'review', '碳减排', '审批', '活动'],
        ],
        [
            'id' => 'products',
            'label' => 'Reward Store',
            'route' => '/admin/products',
            'description' => 'Manage redemption products, inventory and pricing.',
            'keywords' => ['store', 'product', '奖励', '兑换'],
        ],
        [
            'id' => 'badges',
            'label' => 'Badge Management',
            'route' => '/admin/badges',
            'description' => 'Create, edit and award achievement badges.',
            'keywords' => ['badge', '荣誉', '勋章', 'create badge', '颁发'],
        ],
        [
            'id' => 'avatars',
            'label' => 'Avatar Library',
            'route' => '/admin/avatars',
            'description' => 'Manage avatar assets and default selections.',
            'keywords' => ['avatar', '头像'],
        ],
        [
            'id' => 'exchanges',
            'label' => 'Exchange Orders',
            'route' => '/admin/exchanges',
            'description' => 'Review redemption requests and update fulfilment status.',
            'keywords' => ['order', 'exchange', '兑换申请', '物流'],
        ],
        [
            'id' => 'broadcast',
            'label' => 'Broadcast Center',
            'route' => '/admin/broadcast',
            'description' => 'Compose and send system broadcast messages.',
            'keywords' => ['broadcast', '通知', 'announcement', '群发'],
        ],
        [
            'id' => 'systemLogs',
            'label' => 'System Logs',
            'route' => '/admin/system-logs',
            'description' => 'Inspect audit logs and request traces.',
            'keywords' => ['log', '日志', '监控', '审计'],
        ],
    ],
    'quickActions' => [
        [
            'id' => 'search-users',
            'label' => 'Search users',
            'description' => 'Focus the user search box for quick lookup.',
            'routeId' => 'users',
            'route' => '/admin/users',
            'mode' => 'shortcut',
            'query' => ['focus' => 'search'],
            'keywords' => ['search user', 'find user', '查找用户', '搜用户'],
        ],
        [
            'id' => 'create-badge',
            'label' => 'Create new badge',
            'description' => 'Open the badge creation modal.',
            'routeId' => 'badges',
            'route' => '/admin/badges',
            'mode' => 'shortcut',
            'query' => ['create' => '1'],
            'keywords' => ['new badge', 'badge builder', '创建徽章'],
        ],
        [
            'id' => 'pending-activities',
            'label' => 'Review pending activities',
            'description' => 'Filter activity review list to pending items.',
            'routeId' => 'activities',
            'route' => '/admin/activities',
            'mode' => 'shortcut',
            'query' => ['filter' => 'pending'],
            'keywords' => ['待审批', 'pending', '审核活动'],
        ],
        [
            'id' => 'compose-broadcast',
            'label' => 'Compose broadcast',
            'description' => 'Open the broadcast composer.',
            'routeId' => 'broadcast',
            'route' => '/admin/broadcast',
            'mode' => 'shortcut',
            'query' => ['compose' => '1'],
            'keywords' => ['广播', 'announcement', 'new broadcast'],
        ],
    ],
    'managementActions' => [
        [
            'name' => 'approve_carbon_records',
            'label' => 'Approve carbon reduction records',
            'description' => 'Approve one or more pending carbon reduction activity submissions by record id.',
            'api' => [
                'method' => 'PUT',
                'path' => '/api/v1/admin/activities/review',
                'payloadTemplate' => [
                    'action' => 'approve',
                    'record_ids' => [],
                    'review_note' => null,
                ],
            ],
            'requires' => ['record_ids'],
            'contextHints' => ['selectedRecordIds'],
            'autoExecute' => true,
        ],
        [
            'name' => 'reject_carbon_records',
            'label' => 'Reject carbon reduction records',
            'description' => 'Reject one or more pending carbon reduction records with an optional note.',
            'api' => [
                'method' => 'PUT',
                'path' => '/api/v1/admin/activities/review',
                'payloadTemplate' => [
                    'action' => 'reject',
                    'record_ids' => [],
                    'review_note' => null,
                ],
            ],
            'requires' => ['record_ids'],
            'contextHints' => ['selectedRecordIds'],
            'autoExecute' => true,
        ],
    ],
];

