CREATE TABLE IF NOT EXISTS admin_ai_runs (
  id int(11) NOT NULL AUTO_INCREMENT,
  run_id varchar(64) NOT NULL,
  conversation_id varchar(64) NOT NULL,
  admin_id int(11) DEFAULT NULL,
  autonomy_mode varchar(32) NOT NULL DEFAULT 'read_only_auto',
  status varchar(24) NOT NULL DEFAULT 'running',
  source varchar(120) DEFAULT NULL,
  request_id varchar(64) DEFAULT NULL,
  error_message text DEFAULT NULL,
  meta_json longtext DEFAULT NULL,
  started_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at datetime DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_ai_runs_run_id (run_id),
  KEY idx_admin_ai_runs_conversation_id (conversation_id),
  KEY idx_admin_ai_runs_status (status),
  KEY idx_admin_ai_runs_started_at (started_at),
  KEY idx_admin_ai_runs_request_id (request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_ai_steps (
  id int(11) NOT NULL AUTO_INCREMENT,
  run_id varchar(64) NOT NULL,
  step_id varchar(80) NOT NULL,
  sequence_no int(11) NOT NULL DEFAULT 0,
  type varchar(32) NOT NULL DEFAULT 'tool',
  tool_name varchar(120) DEFAULT NULL,
  status varchar(24) NOT NULL DEFAULT 'running',
  approval_state varchar(24) DEFAULT NULL,
  rollback_state varchar(24) DEFAULT NULL,
  input_json longtext DEFAULT NULL,
  output_json longtext DEFAULT NULL,
  error_message text DEFAULT NULL,
  started_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finished_at datetime DEFAULT NULL,
  duration_ms decimal(10,2) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_admin_ai_steps_run_step (run_id, step_id),
  KEY idx_admin_ai_steps_run_id (run_id),
  KEY idx_admin_ai_steps_run_sequence (run_id, sequence_no),
  KEY idx_admin_ai_steps_status (status),
  KEY idx_admin_ai_steps_tool_name (tool_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
