CREATE TABLE IF NOT EXISTS `user_passkeys` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `credential_id` varchar(1024) NOT NULL,
  `credential_id_hash` char(64) NOT NULL,
  `credential_type` varchar(32) NOT NULL DEFAULT 'public-key',
  `label` varchar(100) DEFAULT NULL,
  `public_key` longtext NOT NULL,
  `rp_id` varchar(255) NOT NULL,
  `user_handle` varchar(255) NOT NULL,
  `transports` longtext DEFAULT NULL,
  `aaguid` char(36) DEFAULT NULL,
  `sign_count` bigint(20) UNSIGNED NOT NULL DEFAULT 0,
  `attestation_format` varchar(64) DEFAULT NULL,
  `backup_eligible` tinyint(1) NOT NULL DEFAULT 0,
  `backup_state` tinyint(1) NOT NULL DEFAULT 0,
  `meta_json` longtext DEFAULT NULL,
  `last_used_at` datetime DEFAULT NULL,
  `attested_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `disabled_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_passkeys_credential_id_hash` (`credential_id_hash`),
  KEY `idx_user_passkeys_user_id` (`user_id`),
  KEY `idx_user_passkeys_rp_id` (`rp_id`),
  KEY `idx_user_passkeys_disabled_at` (`disabled_at`),
  KEY `idx_user_passkeys_last_used_at` (`last_used_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;

CREATE TABLE IF NOT EXISTS `webauthn_challenges` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `challenge_id` char(36) NOT NULL,
  `user_id` int(11) DEFAULT NULL,
  `flow_type` varchar(32) NOT NULL,
  `challenge` varchar(255) NOT NULL,
  `request_id` varchar(64) DEFAULT NULL,
  `context_json` longtext DEFAULT NULL,
  `expires_at` datetime NOT NULL,
  `consumed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_webauthn_challenges_challenge_id` (`challenge_id`),
  KEY `idx_webauthn_challenges_user_id` (`user_id`),
  KEY `idx_webauthn_challenges_flow_type` (`flow_type`),
  KEY `idx_webauthn_challenges_expires_at` (`expires_at`),
  KEY `idx_webauthn_challenges_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
